### ISSUE TITLE
poobah pkl file is not generated

### ISSUE THREAD

**Issue by moranr7** [FoxoTech/methylprep#59]
Using methylprep version '1.2.11' and command : 
python -m methylprep -v process --all 

I cannot pass the parameter  --export_poobah to the function. 

Any idea what is happening here ? 

Thanks, 
Ray

**Comment by marcmaxson** [comment]
Looking into it. I noticed this too last week, and I assumed (in fact I know) that those p-values are all saved in each file's `processed.csv` in a new column.

But I could have it export those to its own pickle if that works better for you. The `methylcheck.load()` function will respect the p-value column in those CSVs and exclude failing probes if you ask it to.

But I imagine people would want to do this some other way and would need a p_values.pkl dataframe in other situations.

**Comment by marcmaxson** [comment]
I think this is resolved in v1.4.0 now.
